### ISSUE TITLE
simulateTx while calling an method doesn't work

### ISSUE THREAD

**Issue by Yash094** [thirdweb-dev/engine#393]
When passing `simulateTx` as true gets ignored while sending requests to engine , The transaction is suppose to just simulate but is executed instead.

Thanks to myk.eth(@mykcryptodev) for pointing this out.

**Comment by farhanW3** [comment]
Hi @Yash094 

The `simulateTx` flag, will simulate the transaction during the request time and then add it to the queue if the simulation works otherwise if simulation fails, it sends an error back.

Once the request is queued the worker will pick it up and process the request and send transaction on chain.

Thus, you see the transaction being sent on-chain, but Engine does simulate the transaction to check its validity

**Comment by Yash094** [comment]
Okay, that makes sense. Thank you so much for your prompt response
