### ISSUE TITLE
Marketplace 'createListing' - "The transaction failed onchain" intermittent issue

### ISSUE THREAD

**Issue by Kuro182** [thirdweb-dev/engine#733]
We've updated engine version from v0.9.1 to the latest (v2.0.29) and facing intermittent issue while creating listings on MarketplaceV3.

Issue happens if we mint several tokens for ERC1155 and after calling createListing for these tokens - some transactions are failing with 
Error
The transaction failed onchain. See: https://portal.thirdweb.com/engine/troubleshooting

If we create listing just for one token of ERC1155 (TokenId = 0) - all works fine.

Reverted back to v0.9.1 - listings work fine, so it looks like a bug in newest versions.

Also if we trying to call createListing not in engine but in Marketplace Explorer - no issues (First pic)
![image](https://github.com/user-attachments/assets/cab0852f-1b8f-404a-b533-140317772560)
![image](https://github.com/user-attachments/assets/d3f0ff86-9241-40a6-b4b3-ae1368abe54b)

**Comment by Kuro182** [comment]
We've tried to use ?simulateTx=true - got 200 response, and transaction is also Mined, but inside it there is an error.

Also checked transaction hash - there is no useful information in it (here is an example of failed transaction - https://amoy.polygonscan.com/tx/0xe25b9ecc2ed7ef98e5a44fe6c4aca7d4f285fd074c2ca03365aa0852637140b2) and all data is the same as in Successful transaction.

About timing - we've tried to call createListing transactions with 5-10 minutes break between each call and it also fails.

So the only one thing we've noted as i've already said - createListing works fine with v0.9.1 but fails intermittently in newest versions

**Comment by d4mr** [comment]
Hi @Kuro182, we have determined that the revert is caused due to the transaction going out of gas. While we fix this issue, you can circumvent it by specifying a gas override as a part of the `txOverrides` in the request body ([reference](https://thirdweb-engine.apidocumentation.com/reference#tag/marketplace-directlistings/POST/marketplace/%7Bchain%7D/%7BcontractAddress%7D/direct-listings/create-listing)). For the transaction you reference [here](https://amoy.polygonscan.com/tx/0xe25b9ecc2ed7ef98e5a44fe6c4aca7d4f285fd074c2ca03365aa0852637140b2), a value of `280,000` should be safe.

**Comment by Kuro182** [comment]
Issue moved to closed, but we've checked - issue still persists.
![image](https://github.com/user-attachments/assets/88acfb46-d339-45c9-99ed-114de3aacd28)
